using Bogus;
using FluentResults;
using Microsoft.EntityFrameworkCore;
using TaskTracker.Business.FluentErrors;
using TaskTracker.DataAccess.Databases;
using TaskTracker.DataAccess.Entities;
using TaskTracker.Shared.Constants;
using TaskTracker.Shared.Enums;

namespace TaskTracker.Business.Services.Seeding;

public class DataSeederService(TaskTrackerDbContext db) : IDataSeederService
{
    public async Task<Result> GenerateDefaultDataAsync(Guid userId, int taskAddAmount, int categoryAddAmount)
    {
        int maxCategoryPosition = await db.Categories
            .MaxAsync(c => (int?)c.Position) ?? 0;

        int maxTaskPosition = await db.Tasks
            .MaxAsync(t => (int?)t.Position) ?? 0;

        int tasksCount = await db.Tasks.CountAsync();
        int categoriesCount = await db.Categories.CountAsync();

        if (tasksCount + taskAddAmount > TaskConstraints.MaxTasksForConfirmedEmail)
            return Result.Fail(new TaskLimitExceededError(TaskConstraints.MaxTasksForConfirmedEmail, true));

        if (categoriesCount + categoryAddAmount > CategoryConstraints.MaxCategoriesForConfirmedEmail)
            return Result.Fail(new CategoryLimitExceededError(CategoryConstraints.MaxCategoriesForConfirmedEmail, true));

        // Categories
        var categoryFaker = new Faker<CategoryEntity>()
            .RuleFor(c => c.Id, f => Guid.NewGuid())
            .RuleFor(c => c.Title, f => f.Lorem.Word() + f.UniqueIndex)
            .RuleFor(c => c.Colour, f => f.Internet.Color())
            .RuleFor(c => c.UserId, f => userId)
            .RuleFor(c => c.Position, f => ++maxCategoryPosition);

        var categories = categoryFaker.Generate(categoryAddAmount);

        // Tasks
        var priorities = Enum.GetValues<TaskPriority>();

        var taskFaker = new Faker<TaskEntity>()
            .RuleFor(t => t.Id, f => Guid.NewGuid())
            .RuleFor(t => t.Title, f => f.Lorem.Sentence(f.Random.Int(3, 7)))
            .RuleFor(t => t.Description, f => f.Random.Bool(0.7f) ? f.Lorem.Paragraph() : null)
            .RuleFor(t => t.DueDate, f => f.Random.Bool(0.6f)
                ? DateOnly.FromDateTime(f.Date.Between(DateTime.Now.AddMonths(-1), DateTime.Now.AddYears(1)))
                : null)
            .RuleFor(t => t.Priority, f => f.PickRandom(priorities))
            .RuleFor(t => t.IsCompleted, f => f.Random.Bool(0.3f))
            .RuleFor(t => t.Position, f => ++maxTaskPosition)
            .RuleFor(t => t.UserId, f => userId)
            .RuleFor(t => t.CategoryId, f => f.Random.Bool(0.85f)
                ? f.PickRandom(categories).Id
                : (Guid?)null);
            // CreatedAt will be generated by UpdateTimestamps() in SaveChangesAsync

        var tasks = taskFaker.Generate(taskAddAmount);

        await db.Categories.AddRangeAsync(categories);
        await db.Tasks.AddRangeAsync(tasks);
        try
        {
            await db.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            return Result.Fail(new ExceptionalError(ex));
        }

        return Result.Ok();
    }
}